# Enable CI builds, trigger a build whenever the master branch receive new modifications
trigger:
- 'main'

pool:
  vmImage: 'ubuntu-20.04'

steps:
# Tasks are the building blocks of a pipeline
# We can choose from a catalog of tasks available by default or download from the Azure DevOps marketplace
# In this case I chose to use 6 tasks (not mandatory) to install dependencies and build the App.
  - task: Npm@1 # Run npm install
    displayName: 'npm install'
    inputs:
      command: install
      workingDir: '$(System.DefaultWorkingDirectory)'

  - task: Npm@1 # Run npm run build
    displayName: 'npm run build'
    inputs:
      command: custom
      customCommand: run build

  - script: | # Run cordova build
      npx ionic cordova build android --no-build --release
    displayName: 'ionic cordova build android --no-build --release'

  - publish: 'www/' # Publish App artifact
    artifact: 'www'
    displayName: 'Publishing Artifact'
